In [2]:
import cv2
import numpy as np
import os

In [2]:
def procRPLTRlabelData(dataList, h, w):
    data = np.array(dataList)
    data = np.unique(data, axis=0)
    data = data[:, :5]
    
    print(data)
    
    labels = []
    
    for row in data:
        cls, xMin, yMin, xMax, yMax = row
    
        xCenter = ((xMin + xMax) / 2) / w
        yCenter = ((yMin + yMax) / 2) / h
        bw = (xMax - xMin) / w
        bh = (yMax - yMin) / h
    
        labels.append(f"{int(cls)} {xCenter} {yCenter} {bw} {bh}")

    return labels

In [3]:
def makeImgLabelPair(numTag, img, labelNP, folderName):
    h, w, _ = img.shape
    labelList = labelNP.tolist()

    labels = procRPLTRlabelData(labelList, h, w)

    os.makedirs(f"{folderName}/labels", exist_ok=True)
    os.makedirs(f"{folderName}/images", exist_ok=True)
    
    with open(f"{folderName}/labels/{numTag}.txt", "w") as f:
        f.write("\n".join(labels))
    
    cv2.imwrite(f"{folderName}/images/{numTag}.png", img)
    

In [4]:
def runProcessing():
    for i in range(700):  # 0 → 699
        numTag = str(i).zfill(4)
    
        imagePath = fr"C:/PROJECTS/TrafficLightDetectionTutorial/ReplicatorOutput/rgb_{numTag}.png"
        labelPath = fr"C:/PROJECTS/TrafficLightDetectionTutorial/ReplicatorOutput/bounding_box_2d_tight_{numTag}.npy"
        
        img = cv2.imread(imagePath)
        data = np.load(labelPath)

        if data is None or len(data) == 0:
            print(f"No data on {i}")
            continue
    
        makeImgLabelPair(numTag, img, data, "PrepData")

        print(f"---{i}---")

In [5]:
runProcessing()

[[  0. 236. 273. 259. 297.]
 [  1. 264. 273. 286. 296.]
 [  2. 291. 272. 312. 295.]]
---0---
[[  0. 246. 279. 266. 301.]
 [  1. 271. 279. 292. 301.]
 [  2. 297. 279. 319. 302.]]
---1---
[[  0. 247. 276. 267. 296.]]
---2---
[[  0. 210. 282. 233. 314.]
 [  2. 271. 282. 298. 317.]]
---3---
[[  0. 249. 274. 261. 290.]
 [  2. 280. 275. 293. 291.]]
---4---
[[  2. 310. 290. 330. 312.]]
---5---
[[  2. 266. 275. 298. 310.]]
---6---
[[  0. 222. 289. 251. 318.]
 [  2. 293. 289. 323. 318.]]
---7---
No data on 8
[[  0. 242. 278. 260. 298.]]
---9---
[[  0. 225. 254. 246. 279.]
 [  2. 278. 253. 300. 279.]]
---10---
No data on 11
[[  0. 217. 265. 239. 287.]
 [  1. 244. 265. 265. 287.]
 [  2. 271. 265. 292. 287.]]
---12---
[[  2. 285. 276. 300. 294.]]
---13---
[[  1. 269. 266. 294. 291.]]
---14---
No data on 15
[[  1. 288. 280. 301. 306.]
 [  2. 304. 281. 317. 305.]]
---16---
[[  0. 261. 281. 283. 304.]
 [  2. 317. 281. 340. 304.]]
---17---
[[  0. 182. 266. 229. 315.]
 [  2. 292. 266. 333. 312.]]
---18