In [1]:
import cv2
import numpy as np
import os

In [2]:
def procRPLTRlabelData(dataList, h, w):
    data = np.array(dataList)
    data = np.unique(data, axis=0)
    data = data[:, :5]
    
    print(data)
    
    labels = []
    
    for row in data:
        cls, xMin, yMin, xMax, yMax = row
    
        xCenter = ((xMin + xMax) / 2) / w
        yCenter = ((yMin + yMax) / 2) / h
        bw = (xMax - xMin) / w
        bh = (yMax - yMin) / h
    
        labels.append(f"{int(cls)} {xCenter} {yCenter} {bw} {bh}")

    return labels

In [3]:
def makeImgLabelPair(numTag, img, labelNP, folderName):
    h, w, _ = img.shape
    labelList = labelNP.tolist()

    labels = procRPLTRlabelData(labelList, h, w)

    os.makedirs(f"{folderName}/labels", exist_ok=True)
    os.makedirs(f"{folderName}/images", exist_ok=True)
    
    with open(f"{folderName}/labels/{numTag}.txt", "w") as f:
        f.write("\n".join(labels))
    
    cv2.imwrite(f"{folderName}/images/{numTag}.png", img)
    

In [ ]:
def runProcessing():
    for i in range(700):  # 0 → 499
        numTag = str(i).zfill(4)
    
        imagePath = fr"C:/PROJECTS/TrafficLightDetectionTutorial/ReplicatorOutput/rgb_{numTag}.png"
        labelPath = fr"C:/PROJECTS/TrafficLightDetectionTutorial/ReplicatorOutput/bounding_box_2d_tight_{numTag}.npy"
        
        img = cv2.imread(imagePath)
        data = np.load(labelPath)

        if data is None or len(data) == 0:
            print(f"No data on {i}")
            continue
    
        makeImgLabelPair(numTag, img, data, "PrepData")

        print(f"---{i}---")

In [5]:
runProcessing()

No data on 0
[[  0. 213. 281. 240. 307.]]
---1---
No data on 2
[[  0. 263. 293. 279. 317.]
 [  1. 283. 294. 298. 317.]
 [  2. 303. 294. 317. 317.]]
---3---
[[  0. 245. 277. 260. 305.]]
---4---
[[  1. 264. 282. 276. 303.]
 [  2. 280. 283. 291. 303.]]
---5---
[[  0. 208. 286. 227. 310.]
 [  1. 232. 286. 255. 310.]
 [  2. 261. 287. 284. 311.]]
---6---
[[  0. 234. 271. 260. 297.]
 [  2. 299. 271. 324. 297.]]
---7---
[[  2. 317. 261. 343. 288.]]
---8---
No data on 9
No data on 10
[[  1. 268. 265. 290. 289.]
 [  2. 295. 265. 317. 289.]]
---11---
[[  0. 255. 264. 275. 291.]]
---12---
No data on 13
[[  0. 228. 283. 246. 304.]
 [  2. 275. 284. 295. 305.]]
---14---
[[  1. 237. 300. 270. 339.]
 [  2. 278. 302. 314. 342.]]
---15---
[[  1. 276. 281. 289. 300.]]
---16---
[[  1. 262. 256. 306. 300.]]
---17---
[[  0. 202. 274. 228. 303.]
 [  1. 233. 273. 261. 304.]
 [  2. 267. 273. 296. 304.]]
---18---
No data on 19
[[  0. 214. 278. 235. 307.]]
---20---
[[  1. 274. 290. 293. 316.]
 [  2. 299. 290. 320